version: '3'

tasks:
  run:
    desc: Run the main program
    cmds:
      - source .venv/bin/activate
      - python fincaplab/main.py

  check-format:
    desc: Auto-format code with Ruff
    cmds:
      - .venv/bin/ruff format fincaplab tests

  check:
    desc: Run static analysis (Ruff + Mypy) & try to fix some bug
    cmds:
      - .venv/bin/ruff check --fix fincaplab tests
      - .venv/bin/mypy fincaplab
    ignore_error: true

  check-only:
    desc: Check and fix error if ruff can
    cmds:
      - .venv/bin/ruff check fincaplab tests
      - .venv/bin/mypy fincaplab

  test:
    desc: Run tests
    cmds:
      - source .venv/bin/activate
      - pytest tests/

  deploy:
    desc: Deploy the application (placeholder)
    cmds:
      - |
        if [ ! -d .venv ]; then
          echo "$(date) | Create virtual environment"
          python -m venv .venv
        else
          echo "$(date) | Virtual environment already exists, run 'task clean' to remove it if you want to recreate."
        fi
      - source .venv/bin/activate 
      - pip install --upgrade pip
      - pip install -e .
      - pip install -r requirements.txt
      - cmd: echo "$(date) | FinCapLab Deployed!"
        silent: true

  clean-tests:
    desc: Clean up test logs
    cmds:
      - rm -rf .pytest_cache
      - rm -rf tests/logs

  clean:
    desc: Clean up generated files
    cmds:
      - rm -rf __pycache__ *.pyc *.pyo
      - rm -rf .pytest_cache
      - rm -rf dist build *.egg-info
      - rm -rf logs/