name: Infrastructure Check
on: [push]

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Basic Info
        run: |
          echo "Runner 正在工作！"
          echo "当前用户: $(whoami)"
          free -h  # 看看分配给 Runner 的内存真实情况
          